# Generated by Django 3.0.6 on 2020-05-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=40)),
                ('abbreviation', models.CharField(max_length=8)),
                ('country', models.CharField(max_length=40)),
            ],
        ),
    ]
