INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Alabama', 'AL');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Alaska', 'AK');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'American Samoa', 'AS');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Arizona', 'AZ');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Arkansas', 'AR');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'California', 'CA');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Colorado', 'CO');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Connecticut', 'CT');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Delaware', 'DE');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'District Of Columbia', 'DC');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Federated States Of Micronesia', 'FM');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Florida', 'FL');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Georgia', 'GA');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Guam Gu', 'GU');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Hawaii', 'HI');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Idaho', 'ID');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Illinois', 'IL');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Indiana', 'IN');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Iowa', 'IA');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Kansas', 'KS');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Kentucky', 'KY');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Louisiana', 'LA');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Maine', 'ME');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Marshall Islands', 'MH');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Maryland', 'MD');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Massachusetts', 'MA');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Michigan', 'MI');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Minnesota', 'MN');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Mississippi', 'MS');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Missouri', 'MO');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Montana', 'MT');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Nebraska', 'NE');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Nevada', 'NV');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'New Hampshire', 'NH');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'New Jersey', 'NJ');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'New US', 'NM');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'New York', 'NY');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'North Carolina', 'NC');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'North Dakota', 'ND');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Northern Mariana Islands', 'MP');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Ohio', 'OH');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Oklahoma', 'OK');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Oregon', 'OR');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Palau', 'PW');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Pennsylvania', 'PA');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Puerto Rico', 'PR');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Rhode Island', 'RI');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'South Carolina', 'SC');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'South Dakota', 'SD');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Tennessee', 'TN');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Texas', 'TX');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Utah', 'UT');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Vermont', 'VT');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Virgin Islands', 'VI');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Virginia', 'VA');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Washington', 'WA');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'West Virginia', 'WV');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Wisconsin', 'WI');
INSERT INTO states_state (country, province, abbreviation) VALUES('US', 'Wyoming', 'WY');
